# Generated by Django 4.2 on 2025-04-04 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(help_text='Digite apenas números (7 dígitos)', max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='CRM deve conter exatamente 7 dígitos numéricos', regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
